builtin_interfaces/Time time_stamp  # timestamp when message was sent
string sender_id                    # node name of the sending node
string qr_code_content              # decoded content of the detected QR-Code
float32 qrcode_position_x           # x postion of the center of the QR-Code relative to the middle of the image from -100% to +100%
float32 qrcode_position_y           # y postion of the center of the QR-Code relative to the middle of the image from -100% to +100%